on:
  release:
    types: [created]

jobs:
  release-client:
    name: release client ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: github.event.release.tag_name == 'client'
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          SRC_DIR: "client"
